GAME_START_INTRO_TEXT_KEY = "game_start_opening_text"
GAME_SAVES_KEY = "saves"
REWARD_TYPE_MONEY ="money"
REWARD_TYPE_ITEM = "item"
ABILITY_TYPE_PHYSICAL = "physical"
ABILITY_TYPE_MAGIC = "magic"
ABILITY_TYPE_STATS_HEALTH = "stats_health"
ABILITY_TYPE_STATS_STAMINA = "stats_stamina"
ABILITY_TYPE_STATS_DAMAGE = "stats_damage"
ABILITY_TYPE_STATS_DEFENCE = "stats_defence"
ABILITY_TYPE_STATS_TARG_HEALTH = "stats_target_health"
ABILITY_TYPE_STATS_TARG_STAMINA = "stats_target_stamina"
ABILITY_TYPE_STATS_TARG_DAMAGE = "stats_target_damage"
ABILITY_TYPE_STATS_TARG_DEFENCE = "stats_target_defence"

